spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securecapita?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: admin123

  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always
      continue-on-error: false

